Repository oras-project/oras-java, pull requests merged in 2025-03, with the labels that each got.

#175 Export to OCI layout
  .gitignore
  manifest.json
  src/main/java/land/oras/Config.java
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/OciLayout.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/SupportedAlgorithm.java
  src/test/java/land/oras/IndexTest.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#179 Replace docker.io by registry-1.docker.io when doing api calls
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/ContainerRefTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: bug

#180 Support anonymous request token auth for GHCR
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/auth/BearerTokenProvider.java
  src/test/java/land/oras/RegistryTest.java
Labels: bug

#181 Use library namespace by default for docker.io images
  src/main/java/land/oras/Annotations.java
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/AnnotationsTest.java
  src/test/java/land/oras/ContainerRefTest.java
  src/test/java/land/oras/ManifestTest.java
Labels: chore

#182 Support for platform fields and ensure all manifests are resolved when getting index
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/ManifestDescriptor.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/Const.java
  src/test/java/land/oras/IndexTest.java
  src/test/java/land/oras/ManifestDescriptorTest.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#100 Match group id for domain www.oras.land
  README.md
  pom.xml
Labels: enhancement, breaking

#186 Add reproducible build badge and update examples
  README.md
Labels: documentation

#193 Save descriptor as-is on OCI layout
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/Const.java
  src/test/java/land/oras/RegistryTest.java
Labels: chore

#195 Add support for docker content types
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/Const.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: enhancement

#197 Reuse current HTTP client when refresh the token
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/auth/BearerTokenProvider.java
  src/test/java/land/oras/RegistryWireMockTest.java
  src/test/java/land/oras/auth/BearerTokenProviderTest.java
Labels: chore

#198 Split registry with OCI layout
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/OciLayout.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/OCILayoutWireMockTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: chore, breaking

#199 Cleanup OCI layout
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/utils/Const.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/OCILayoutWireMockTest.java
Labels: chore

#200 Add descriptor class and recursirve OCI layout copy
  src/main/java/land/oras/Config.java
  src/main/java/land/oras/Descriptor.java
  src/main/java/land/oras/Layer.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Referrers.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/ConfigTest.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#201 Cleanup AuthStore
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/auth/AuthStore.java
  src/main/java/land/oras/auth/AuthStoreAuthenticationProvider.java
  src/test/java/land/oras/RegistryWireMockTest.java
  src/test/java/land/oras/auth/AuthStoreAuthenticationProviderTest.java
  src/test/java/land/oras/auth/AuthStoreTest.java
  src/test/java/land/oras/credentials/FileStoreTest.java
Labels: chore

#202 Add layout ref to access descriptor on OCI layout
  .gitignore
  .pre-commit-config.yaml
  pom.xml
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Ref.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/Const.java
  src/main/java/land/oras/utils/SupportedAlgorithm.java
  src/test/java/land/oras/LayoutRefTest.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/resources/oci/artifact/blobs/sha256/44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
  src/test/resources/oci/artifact/blobs/sha256/98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
  src/test/resources/oci/artifact/blobs/sha256/cb1d49baba271af2c56d493d66dddb112ecf1c2c52f47e6f45f3617bb2155d34
  src/test/resources/oci/artifact/index.json
  src/test/resources/oci/artifact/oci-layout
  src/test/resources/oci/empty-artifact/.GITKEEP
Labels: enhancement, breaking

#203 Push blob to OCI layout
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Ref.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/LayoutRefTest.java
  src/test/java/land/oras/OCILayoutTest.java
Labels: enhancement

#205 Create OCI layout and various OCILayoutTest cleanup
  src/main/java/land/oras/OCILayout.java
  src/test/java/land/oras/OCILayoutTest.java
Labels: tests, chore

#206 Validate digest when pushing blobs
  pom.xml
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: enhancement

#208 Push artifact to OCI layout
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/ManifestDescriptor.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Ref.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: enhancement

#212 Index is now a descriptor
  src/main/java/land/oras/Descriptor.java
  src/main/java/land/oras/Index.java
Labels: chore

#214 Push up size, digest and artifact type on descriptor
  src/main/java/land/oras/Config.java
  src/main/java/land/oras/Descriptor.java
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/Layer.java
  src/main/java/land/oras/Manifest.java
  src/test/java/land/oras/ConfigTest.java
  src/test/java/land/oras/IndexTest.java
  src/test/java/land/oras/ManifestDescriptorTest.java
  src/test/java/land/oras/OCILayoutTest.java
Labels: chore

#217 Use FileChannel.map for efficient digest computation
  src/main/java/land/oras/utils/DigestUtils.java
Labels: enhancement

#218 Manifest annotations where not copied to index
  src/main/java/land/oras/Annotations.java
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/utils/Const.java
  src/main/java/land/oras/utils/JsonUtils.java
  src/test/java/land/oras/IndexTest.java
  src/test/java/land/oras/OCILayoutTest.java
Labels: bug

#220 Support for index subject
  src/main/java/land/oras/Config.java
  src/main/java/land/oras/Descriptor.java
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/Layer.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/ManifestDescriptor.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/IndexTest.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#221 Push attach artifact into OCI API
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Ref.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/LayoutRefTest.java
  src/test/java/land/oras/ManifestTest.java
  src/test/java/land/oras/OCILayoutTest.java
Labels: enhancement

#222 Add user agent header
  pom.xml
  src/main/java/land/oras/utils/Const.java
  src/main/java/land/oras/utils/OrasHttpClient.java
  src/main/resources/.GITKEEP
  src/main/resources/version.properties
Labels: chore

#228 Update readme version for reproducible builds
  README.md
Labels: documentation

#227 add getter for algoritm name
  src/main/java/land/oras/utils/SupportedAlgorithm.java
  src/test/java/land/oras/utils/SupportedAlgorithmTest.java
Labels: chore
