Repository oras-project/oras-java, pull requests merged in 2025-02, with the labels that each got.

#80 Workflow dispatch for release
  .github/workflows/release.yml
Labels: skip-changelog

#81 Add missing scm and release plugin
  .github/workflows/release.yml
  pom.xml
Labels: chore

#83 Setup SSH key
  .github/workflows/release.yml
  pom.xml
Labels: skip-changelog

#84 Fix version on pom.xml
  .github/workflows/release.yml
  .mvn/maven.config
  README.md
  pom.xml
Labels: skip-changelog

#85 Fix release workflow
  .github/workflows/release.yml
Labels: chore

#60 Add stream API methods
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/DigestUtils.java
  src/main/java/land/oras/utils/OrasHttpClient.java
  src/test/java/land/oras/RegistryTest.java
Labels: chore

#88 Sign snaphosts
  .github/workflows/deploy-snapshots.yml
  pom.xml
Labels: chore

#89 Pass sign-only profile
  .github/workflows/deploy-snapshots.yml
Labels: chore

#90 Add central settings
  .github/workflows/deploy-snapshots.yml
  .github/workflows/release.yml
Labels: chore

#56 Support for file store authentication (docker login)
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Layer.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/auth/BearerTokenProvider.java
  src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
  src/main/java/land/oras/credentials/FileStore.java
  src/main/java/land/oras/exception/Error.java
  src/main/java/land/oras/exception/OrasException.java
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/main/java/land/oras/utils/DigestUtils.java
  src/main/java/land/oras/utils/JsonUtils.java
  src/main/java/land/oras/utils/OrasHttpClient.java
  src/test/java/land/oras/RegistryContainerTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/auth/BearerTokenProviderTest.java
  src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
  src/test/java/land/oras/credentials/FileStoreTest.java
Labels: chore

#92 Ensure to test againts a private registry
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
  src/main/java/land/oras/credentials/FileStore.java
  src/main/java/land/oras/utils/OrasHttpClient.java
  src/test/java/land/oras/RegistryContainerTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
  src/test/java/land/oras/credentials/FileStoreTest.java
  src/test/java/land/oras/utils/RegistryContainer.java
Labels: tests, chore

#93 Fix docker auth and implement test for it
  pom.xml
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
  src/main/java/land/oras/credentials/FileStore.java
  src/test/java/land/oras/RegistryContainerTest.java
  src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
  src/test/java/land/oras/credentials/FileStoreTest.java
Labels: tests, chore

#97 Restore 0.1.1-SNAPSHOT
  pom.xml
Labels: skip-changelog

#98 Revert release
  pom.xml
Labels: skip-changelog

#99 Write permission for content on release
  .github/workflows/release.yml
Labels: skip-changelog

#101 Add sigstore signature for snapshot and releases
  .github/workflows/deploy-snapshots.yml
  pom.xml
Labels: chore

#102 Fix id-token permission
  .github/workflows/deploy-snapshots.yml
  .github/workflows/release.yml
Labels: skip-changelog

#104 Add license plugin and insert license header on all sources
  pom.xml
  src/main/java/land/oras/Annotations.java
  src/main/java/land/oras/Config.java
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Layer.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/Tags.java
  src/main/java/land/oras/auth/AbstractUsernamePasswordProvider.java
  src/main/java/land/oras/auth/AuthProvider.java
  src/main/java/land/oras/auth/BearerTokenProvider.java
  src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
  src/main/java/land/oras/auth/NoAuthProvider.java
  src/main/java/land/oras/auth/UsernamePasswordProvider.java
  src/main/java/land/oras/credentials/FileStore.java
  src/main/java/land/oras/exception/Error.java
  src/main/java/land/oras/exception/OrasException.java
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/main/java/land/oras/utils/Const.java
  src/main/java/land/oras/utils/DigestUtils.java
  src/main/java/land/oras/utils/JsonUtils.java
  src/main/java/land/oras/utils/OrasHttpClient.java
  src/test/java/land/oras/AnnotationsTest.java
  src/test/java/land/oras/ContainerRefTest.java
  src/test/java/land/oras/LayerTest.java
  src/test/java/land/oras/ManifestTest.java
  src/test/java/land/oras/RegistryContainerTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
  src/test/java/land/oras/auth/BearerTokenProviderTest.java
  src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
  src/test/java/land/oras/credentials/FileStoreTest.java
  src/test/java/land/oras/utils/DigestUtilsTest.java
  src/test/java/land/oras/utils/RegistryContainer.java
Labels: chore

#105 Fix flaky tests
  src/test/java/land/oras/RegistryContainerTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
  src/test/java/land/oras/utils/RegistryContainer.java
  src/test/resources/logback-test.xml
Labels: tests

#106 Reproducible builds
  pom.xml
Labels: chore

#108 Allow file store provider to select credentials
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/auth/AbstractUsernamePasswordProvider.java
  src/main/java/land/oras/auth/AuthProvider.java
  src/main/java/land/oras/auth/BearerTokenProvider.java
  src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
  src/main/java/land/oras/auth/NoAuthProvider.java
  src/main/java/land/oras/utils/OrasHttpClient.java
  src/test/java/land/oras/ContainerRefTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
  src/test/java/land/oras/auth/BearerTokenProviderTest.java
  src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
Labels: chore

#109 Podman/buildhah auth
  src/main/java/land/oras/credentials/FileStore.java
  src/test/java/land/oras/RegistryWireMockTest.java
  src/test/java/land/oras/credentials/FileStoreTest.java
Labels: chore

#111 Add Security ossf scorecard
  .github/workflows/scorecard.yml
Labels: chore

#112 Fix missing v prefix on workflow tag
  .github/workflows/scorecard.yml
Labels: skip-changelog

#113 Add some OSS badges
  README.md
Labels: documentation

#115 Add precommit action to PR build
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/pull_request_template.md
  .github/workflows/build.yml
  .gitignore
  .pre-commit-config.yaml
Labels: skip-changelog

#116 Avoid permission at workflow level
  .github/workflows/deploy-javadoc.yml
  .github/workflows/deploy-snapshots.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: skip-changelog

#117 Add codecov on main branch
  .github/workflows/deploy-snapshots.yml
  README.md
Labels: chore

#118 Fix jacoco location
  .github/workflows/deploy-snapshots.yml
Labels: skip-changelog

#119 Run jacoco on sign-only-profile
  pom.xml
Labels: skip-changelog

#120 Rename sign-only to sign-profile and don't skipTests by default
  .github/workflows/deploy-snapshots.yml
  pom.xml
Labels: skip-changelog

#121 Add codecov config
  .github/.codecov.yml
  README.md
Labels: skip-changelog

#122 Use setup java action for package detection
  .github/workflows/deploy-snapshots.yml
Labels: skip-changelog

#123 Increase coverage for archive and digests
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/main/java/land/oras/utils/DigestUtils.java
  src/test/java/land/oras/utils/ArchiveUtilsTest.java
  src/test/java/land/oras/utils/DigestUtilsTest.java
Labels: tests

#124 Add codecov on PR build
  .github/.codecov.yml
  .github/workflows/build.yml
Labels: chore

#131 Fix few issue with `ArchiveUtils` (empty dir, symlink, permissions) and increase overall coverage
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
  src/test/java/land/oras/auth/UsernamePasswordProviderTest.java
  src/test/java/land/oras/exception/ErrorTest.java
  src/test/java/land/oras/exception/OrasExceptionTest.java
  src/test/java/land/oras/utils/ArchiveUtilsTest.java
Labels: bug, tests

#132 Increase to 80% coverage
  .github/.codecov.yml
  src/main/java/land/oras/utils/JsonUtils.java
  src/test/java/land/oras/LayerTest.java
  src/test/java/land/oras/utils/JsonUtilsTest.java
Labels: tests

#133 Update jar and signature to release
  .github/workflows/release.yml
Labels: chore

#134 Maven release sign commits
  .github/workflows/release.yml
Labels: skip-changelog

#135 Fetch again release_id and add logs
  .github/workflows/release.yml
Labels: chore

#136 Add common builder method defaults and insecure
  README.md
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/auth/AbstractUsernamePasswordProvider.java
  src/main/java/land/oras/auth/BearerTokenProvider.java
  src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
  src/main/java/land/oras/auth/NoAuthProvider.java
  src/main/java/land/oras/auth/UsernamePasswordProvider.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#137 Artifacts are now also uploaded on GitHub release
  .github/workflows/release.yml
Labels: chore

#140 Add contributing guide
  .github/pull_request_template.md
  src/CONTRIBUTING.md
Labels: documentation

#142 Better OCI compatibility
  src/main/java/land/oras/Config.java
  src/main/java/land/oras/Layer.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/Const.java
  src/main/java/land/oras/utils/JsonUtils.java
  src/test/java/land/oras/ConfigTest.java
  src/test/java/land/oras/ManifestTest.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#144 Missing extraction on pullArtifact
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/utils/ArchiveUtilsTest.java
Labels: bug

#145 Simple implementation of copy
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#146 Fix contributing location
  CONTRIBUTING.md
Labels: documentation

#148 Add support for SHA-512 hash
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Layer.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/DigestUtils.java
  src/main/java/land/oras/utils/SupportedAlgorithm.java
  src/test/java/land/oras/ContainerRefTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/utils/DigestUtilsTest.java
Labels: enhancement

#150 Add support for io.deis.oras.content.digest annotation
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/main/java/land/oras/utils/Const.java
  src/main/java/land/oras/utils/SupportedAlgorithm.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/utils/ArchiveUtilsTest.java
  src/test/java/land/oras/utils/SupportedAlgorithmTest.java
Labels: enhancement

#152 Partial support for referals
  src/main/java/land/oras/Config.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/ManifestDescriptor.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/Subject.java
  src/main/java/land/oras/utils/Const.java
  src/test/java/land/oras/ManifestTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/SubjectTest.java
Labels: enhancement

#153 Implement /referrers endpoint
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/ManifestDescriptor.java
  src/main/java/land/oras/Referrers.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/utils/Const.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#157 Allow setting media type
  src/main/java/land/oras/LocalPath.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/LocalPathTest.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement, breaking

#161 Add `.sdkmanrc` and update contributing guide
  .sdkmanrc
  CONTRIBUTING.md
Labels: documentation

#169 Add support for attach utility
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#170 Support for no compression for directories
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/main/java/land/oras/utils/DigestUtils.java
  src/main/java/land/oras/utils/SupportedAlgorithm.java
  src/main/java/land/oras/utils/SupportedCompression.java
  src/test/java/land/oras/RegistryTest.java
Labels: chore

#171 Validation of artifactType
  src/main/java/land/oras/ArtifactType.java
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/ArtifactTypeTest.java
  src/test/java/land/oras/ManifestTest.java
  src/test/java/land/oras/RegistryTest.java
Labels: chore, breaking
