Repository oras-project/oras-java, pull requests merged in 2025-04, with the labels that each got.

#239 Push up pushIndex and prepare for reusable copy methods
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/LayoutRefTest.java
  src/test/java/land/oras/OCILayoutTest.java
Labels: chore

#240 Reduce some code duplicate with Describable interface
  src/main/java/land/oras/Describable.java
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/OCILayout.java
  src/test/java/land/oras/LayoutRefTest.java
  src/test/java/land/oras/OCILayoutTest.java
Labels: chore

#241 Pull config utils
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/OCILayoutWireMockTest.java
Labels: chore

#244 Push up collect layer
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Registry.java
Labels: chore

#245 Get referrences from OCI Layout
  src/main/java/land/oras/Describable.java
  src/main/java/land/oras/Index.java
  src/main/java/land/oras/Manifest.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Referrers.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/resources/oci/subject/blobs/sha256/44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
  src/test/resources/oci/subject/blobs/sha256/98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
  src/test/resources/oci/subject/blobs/sha256/bb329f103a5fd68e96771f7dcfaa7722e9ec727bb9ab83c2beee96d6f25b08d6
  src/test/resources/oci/subject/blobs/sha256/ccec2a2be7ce7c6aadc8ed0dc03df8f91cbd3534272dd1f8284226a8d3516dd6
  src/test/resources/oci/subject/blobs/sha256/e094bc809626f0a401a40d75c56df478e546902ff812772c4594265203b23980
  src/test/resources/oci/subject/index.json
  src/test/resources/oci/subject/oci-layout
Labels: enhancement

#246 Move to generic copy
  .pre-commit-config.yaml
  src/main/java/land/oras/CopyUtils.java
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/OCILayout.java
  src/test/java/land/oras/LayoutRefTest.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/resources/oci/subject/blobs/sha256/44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
  src/test/resources/oci/subject/blobs/sha256/bb329f103a5fd68e96771f7dcfaa7722e9ec727bb9ab83c2beee96d6f25b08d6
  src/test/resources/oci/subject/blobs/sha256/ccec2a2be7ce7c6aadc8ed0dc03df8f91cbd3534272dd1f8284226a8d3516dd6
  src/test/resources/oci/subject/index.json
  src/test/resources/oci/subject/oci-layout
Labels: enhancement

#247 Ensure to push blobs and config before manifests
  src/main/java/land/oras/CopyUtils.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#254 Fix overwrite for pullArtifact
  src/main/java/land/oras/CopyUtils.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/RegistryTest.java
Labels: bug

#255 Do not fail if XDG_RUNTIME_DIR is not set
  src/main/java/land/oras/auth/AuthStore.java
  src/test/java/land/oras/auth/AuthStoreTest.java
Labels: bug

#256 Support for getting tags on OCI layout
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: enhancement, breaking

#257 Add support for sha384
  src/main/java/land/oras/utils/SupportedAlgorithm.java
  src/test/java/land/oras/LayerTest.java
  src/test/java/land/oras/utils/SupportedAlgorithmTest.java
Labels: enhancement

#260 Quick build profile
  pom.xml
Labels: chore

#261 Store registry URL into registry
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/ContainerRefTest.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: enhancement

#262 Allow to copy layout from from OCI layout
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/OCI.java
  src/test/java/land/oras/LayoutRefTest.java
Labels: enhancement

#268 add RateLimitng and Concurrency Tests in RegistryWireMockTest
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: tests

#270 Add support for integration tests and fix some issue with docker.io and GHCR
  pom.xml
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/utils/HttpClient.java
  src/test/java/land/oras/ContainerRefTest.java
  src/test/java/land/oras/DockerIoITCase.java
  src/test/java/land/oras/GitHubContainerRegistryITCase.java
Labels: bug, tests

#275 List repositories
  src/main/java/land/oras/ContainerRef.java
  src/main/java/land/oras/OCI.java
  src/main/java/land/oras/OCILayout.java
  src/main/java/land/oras/Registry.java
  src/main/java/land/oras/Repositories.java
  src/test/java/land/oras/ContainerRefTest.java
  src/test/java/land/oras/OCILayoutTest.java
  src/test/java/land/oras/RegistryTest.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: enhancement

#276 Remove resource for better Quarkus support
  pom.xml
  src/main/generated/Versions.java
  src/main/java/land/oras/auth/HttpClient.java
  src/main/java/land/oras/utils/Const.java
  src/main/resources/version.properties
Labels: chore

#278 Fix javadoc build
  .github/workflows/deploy-javadoc.yml
Labels: chore

#283 Fix tar/untar to never add current dir entry and avoid traversal attacks
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/test/java/land/oras/utils/ArchiveUtilsTest.java
Labels: bug, security

#284 Add SHA1 utils
  src/main/java/land/oras/utils/SupportedAlgorithm.java
  src/test/java/land/oras/utils/SupportedAlgorithmTest.java
Labels: chore

#285 Add two annotation constants
  src/main/java/land/oras/utils/Const.java
  src/test/java/land/oras/utils/ConstTest.java
Labels: chore

#287 Convenience methods for layout ref
  src/main/generated/Versions.java
  src/main/java/land/oras/LayoutRef.java
  src/main/java/land/oras/Ref.java
  src/test/java/land/oras/OCILayoutTest.java
Labels: chore

#288 Mention Quarkus ORAS
  README.md
Labels: documentation

#289 Add more convenience methods on registry
  src/main/java/land/oras/Registry.java
  src/test/java/land/oras/RegistryTest.java
Labels: enhancement

#291 Add some convenience methods on archive utils
  src/main/java/land/oras/utils/ArchiveUtils.java
  src/test/java/land/oras/utils/ArchiveUtilsTest.java
Labels: chore

#292 Missing redirect after getting auth token
  src/main/java/land/oras/auth/HttpClient.java
  src/test/java/land/oras/DockerIoITCase.java
  src/test/java/land/oras/GitHubContainerRegistryITCase.java
  src/test/java/land/oras/JFrogArtifactoryITCase.java
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: bug

#295 add NetworkConnectivity and CorruptedResponses Tests using Wiremock
  src/test/java/land/oras/RegistryWireMockTest.java
Labels: tests
