Repository oras-project/oras-java, pull requests merged in 2025-01, with the labels that each got.

#48 Finalize transfer and fix URL in pom.xml for distribution on GH packages
  .github/CODEOWNERS
  .github/dependabot.yml
  pom.xml
Labels: chore

#51 Added pull_request_template
  .github/pull_request_template.md
Labels: chore

#58 Enable spotless
  pom.xml
Labels: chore

#59 Fix spotless check during build
  pom.xml
Labels: chore

#62 Add release drafter workflow
  .github/workflows/release-drafter.yml
Labels: chore

#68 Fix workflow permission
  .github/workflows/deploy-javadoc.yml
Labels: skip-changelog

#69 Rename job name
  .github/workflows/deploy-javadoc.yml
Labels: skip-changelog

#71 Add link for Javadoc on readme
  README.md
Labels: documentation
